<a href="https://colab.research.google.com/github/alvinkur/Scientific-Computing/blob/main/2802415435_ALVIN_KURNIAWAN_ALIANTO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
x = 10
x

10

In [ ]:
x = x + 1
x

11

In [ ]:
x = x + 10
x

21

In [ ]:
x = 1
y = x + 1
x = 2
y

2

In [ ]:
import numpy as np

In [ ]:
x = np.array([1,4,3])
x

array([1, 4, 3])

In [ ]:
x = np.array([1,4,3,9,2,7])
y = x.reshape(2,3)
y

array([[1, 4, 3],
       [9, 2, 7]])

In [ ]:
x = np.array([[1,4,3],[9,2,7]])
x

array([[1, 4, 3],
       [9, 2, 7]])

In [ ]:
def my_adder(a,b,c):

      out = a+b+c
      return out

In [ ]:
my_adder(68,82,19)

169

In [ ]:
def my_thermo_stat(temp, desired_temp):
    if temp < desired_temp - 5:
        status = 'Heat'
    elif temp > desired_temp + 5:
        status = 'AC'
    else:
        status = 'Off'
    return status

In [ ]:
status = my_thermo_stat(32,38)
print(status)

Heat


In [ ]:
status = my_thermo_stat(96,51)
print(status)

AC


In [ ]:
status = my_thermo_stat(66,64)
print(status)

Off


In [ ]:
x = 3
if 1 < x < 2:
  y = 2
elif 2 < x < 4:
  y = 4
else:
  y = 0
print(y)

4
